### ISSUE TITLE
encounter two errors while running train.py

### ISSUE THREAD

**Issue by galaxysltr** [iGangao/TREC2022-passage_rerank#1]
When I run the train.py, I always encounter these errors. How can I solve them? Thank you.
![error1](https://github.com/iGangao/TREC2022-passage_rerank/assets/60500104/4a33df2c-907c-4240-bd12-84aa787cbe7f)
![error2](https://github.com/iGangao/TREC2022-passage_rerank/assets/60500104/70b4298a-c332-4767-aea9-e15ef4b6bdc5)

**Comment by iGangao** [comment]
> When I run the train.py, I always encounter these errors. How can I solve them? Thank you. ![error1](https://private-user-images.githubusercontent.com/60500104/291327522-4a33df2c-907c-4240-bd12-84aa787cbe7f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTQyNzQsIm5iZiI6MTcwMjkxMzk3NCwicGF0aCI6Ii82MDUwMDEwNC8yOTEzMjc1MjItNGEzM2RmMmMtOTA3Yy00MjQwLWJkMTItODRhYTc4N2NiZTdmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE1MzkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MmNkMmU5ZjA2NDVlNjljYTQ1MzEzMWFlOGVkODI4MjU0N2NlNWViMDhjOTIwNDZkZGNhOTMyNDNmYjFhZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SyvMF5ZVZSTbPN14qZ1w1RTGgEJStq-5-8da9XG2ylY) ![error2](https://private-user-images.githubusercontent.com/60500104/291327501-70b4298a-c332-4767-aea9-e15ef4b6bdc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTQyNzQsIm5iZiI6MTcwMjkxMzk3NCwicGF0aCI6Ii82MDUwMDEwNC8yOTEzMjc1MDEtNzBiNDI5OGEtYzMzMi00NzY3LWFlYTktZTE1ZWY0YjZiZGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE1MzkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NjRiOTY5OGU5YzUzZTYzOGFhYmZlOTUyN2NlN2E4NjM2ZWFhYWVjNGE5MDVkNzBiNTczNjEyMGU4ODQ2MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fNR4MtggCCk_sAt0Wx3jL4ALLhWK4XwgNTMiMvYi6ZU)

Download all-mpnet-base-v2 model from huggingface(https://huggingface.co/sentence-transformers/all-mpnet-base-v2) and configure the path before running it

**Comment by galaxysltr** [comment]
thank you!
